
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: linting
        run: npm run full-lint

      - name: jest test
        run: npm run test

      - name: Run the tests and generate coverage report 
        run: npm test -- --coverage
   
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install dependency
        run: npm install 
      
      - name: build project
        run: npm run build
      
      - name: e2e test
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          headless: true
          start: npm run serve 
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          config: video=true,videoUploadOnPasses=false

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

