
name: CI/CD

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: linting
        run: npm run full-lint

      - name: jest test
        run: npm run test

      - name: Run the tests and generate coverage report 
        run: npm test -- --coverage
   
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install dependency
        run: npm install 
      
      - name: build project
        run: npm run build
      
      - name: e2e test
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          headless: true
          start: npm run serve 
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          config: video=true,videoUploadOnPasses=false

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]   
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}    

      - name: install dependency
        run: npm install
        
      - name: build project
        run: npm run build
      
      - name: deploy on github pages
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}

